version: "3"
services:
  meilisearch:
    image: getmeili/meilisearch
    command: meilisearch --master-key=${APP_KEYS}
    volumes:
      - ../meilisearch/data.ms:/data.ms
    ports:
      - "7700:7700"
